### ISSUE TITLE
I follow the steps but no result

### ISSUE THREAD

**Issue by anassakr** [ndunnett/foxconnect#1]
![1](https://github.com/ndunnett/foxconnect/assets/109624657/c5de9fda-8872-4b67-9055-edc78abe5645)
![2](https://github.com/ndunnett/foxconnect/assets/109624657/509796c6-293b-4a03-8b50-26fec9e15972)
![3](https://github.com/ndunnett/foxconnect/assets/109624657/cf490e44-2224-41bd-abc7-93c9686dcca3)

**Comment by ndunnett** [comment]
That's just the default landing page, the main application is the "search" page, but it looks like your ICC config dumps are in a different format to what I'm dealing with so there will be no data. The files I've designed it to parse are in a file structure like `icc_git_dumps/<CP name>/<compound name>/<block name>.txt` and have contents like this, for example:

```
NAME   = COMPOUND_NAME:BLOCK_NAME
  TYPE   = AIN
  DESCRP = 
  PERIOD = 2
  PHASE  = 1
  LOOPID = 
  IOMOPT = 1
  IOM_ID = IOM001
  PNT_NO = 1
  SCI    = 3
  HSCO1  = 55
  LSCO1  = 45
  DELTO1 = .1
  EO1    = HZ
  OSV    = 2.0
  EXTBLK = 0
  MA     = 1
  INITMA = 1
  BADOPT = 3
  LASTGV = 1
  INHOPT = 0
  INHIB  = 0
  INHALM = 0x0
  MANALM = 0
  MTRF   = 1.0
  FLOP   = 0
  FTIM   = 0.0
  XREFOP = 0
  XREFIN = 0.0
  KSCALE = 1.0
  BSCALE = 0.0
  BAO    = 0
  BAT    = 
  BAP    = 5
  BAG    = 1
  ORAO   = 0
  ORAT   = 
  ORAP   = 5
  ORAG   = 1
  HLOP   = 0
  ANM    = 
  HAL    = 100.0
  HAT    = 
  LAL    = 0.0
  LAT    = 
  HLDB   = 0.0
  HLPR   = 5
  HLGP   = 1
  HHAOPT = 0
  HHALIM = 100.0
  HHATXT = 
  LLALIM = 0.0
  LLATXT = 
  HHAPRI = 5
  HHAGRP = 1
  PROPT  = 0
  MEAS   = 49.954101562
  AMRTIN = 0
  NASTDB = 0
  NASOPT = 0
END
```

This may be site specific, it is a set of scripts from Foxboro which generates these configuration files. I've not worked on any other Foxboro I/A control system to know for sure, but this may have been something they have only delivered for this specific customer which is operating with an old unix version of ICC.

Are the contents of your `.icc` files in plain text? I may be able to modify the parser to work with them for you.

**Comment by anassakr** [comment]
Yes, it is a plain text but the in my case there is a file per each CP, and inside this file are the blocks.

**Comment by anassakr** [comment]
If you update your script to read the CP file icc, this will be much easier.

**Comment by ndunnett** [comment]
The control system I work with does not have `.icc` files, can you post a sample?
